import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';

import { ExamsComponent } from './components/exams/exams.component';
import { HomeComponent } from './components/home/home.component';
import { ProblemsComponent } from './components/problems/problems.component';
import { AboutComponent } from './components/about/about.component';
import { LoginComponent } from './components/login/login.component';
import { SignupComponent } from './components/signup/signup.component';
import { ProfileComponent } from './components/profile/profile.component';
import { ContactComponent } from './components/contact/contact.component';
import { TestExamComponent } from './components/test-exam/test-exam.component';
import { TX22G3MExamComponent } from './components/TX22G3M-exam/TX22G3M-exam.component';
import { TX22G3MKeyComponent } from './components/TX22G3M-key/TX22G3M-key.component';
import { TX21G3MExamComponent } from './components/TX21G3M-exam/TX21G3M-exam.component';
import { TX21G3MKeyComponent } from './components/TX21G3M-key/TX21G3M-key.component';
import { TX19G3MExamComponent } from './components/TX19G3M-exam/TX19G3M-exam.component';
import { TX19G3MKeyComponent } from './components/TX19G3M-key/TX19G3M-key.component';
import { TX18G3MExamComponent } from './components/TX18G3M-exam/TX18G3M-exam.component';
import { TX18G3MKeyComponent } from './components/TX18G3M-key/TX18G3M-key.component';
import { TX17G3MExamComponent } from './components/TX17G3M-exam/TX17G3M-exam.component';
import { TX17G3MKeyComponent } from './components/TX17G3M-key/TX17G3M-key.component';
import { TX22G4MExamComponent } from './components/TX22G4M-exam/TX22G4M-exam.component';
import { TX22G4MKeyComponent } from './components/TX22G4M-key/TX22G4M-key.component';
import { TX21G4MExamComponent } from './components/TX21G4M-exam/TX21G4M-exam.component';
import { TX21G4MKeyComponent } from './components/TX21G4M-key/TX21G4M-key.component';
import { TX19G4MExamComponent } from './components/TX19G4M-exam/TX19G4M-exam.component';
import { TX19G4MKeyComponent } from './components/TX19G4M-key/TX19G4M-key.component';
import { TX18G4MExamComponent } from './components/TX18G4M-exam/TX18G4M-exam.component';
import { TX18G4MKeyComponent } from './components/TX18G4M-key/TX18G4M-key.component';
import { TX17G4MExamComponent } from './components/TX17G4M-exam/TX17G4M-exam.component';
import { TX17G4MKeyComponent } from './components/TX17G4M-key/TX17G4M-key.component';
import { TX22G5SExamComponent } from './components/TX22G5S-exam/TX22G5S-exam.component';
import { TX22G5SKeyComponent } from './components/TX22G5S-key/TX22G5S-key.component';
import { TX21G5SExamComponent } from './components/TX21G5S-exam/TX21G5S-exam.component';
import { TX21G5SKeyComponent } from './components/TX21G5S-key/TX21G5S-key.component';
import { TX19G5SExamComponent } from './components/TX19G5S-exam/TX19G5S-exam.component';
import { TX19G5SKeyComponent } from './components/TX19G5S-key/TX19G5S-key.component';
import { TX18G5SExamComponent } from './components/TX18G5S-exam/TX18G5S-exam.component';
import { TX18G5SKeyComponent } from './components/TX18G5S-key/TX18G5S-key.component';
import { TX22G8SExamComponent } from './components/TX22G8S-exam/TX22G8S-exam.component';
import { TX22G8SKeyComponent } from './components/TX22G8S-key/TX22G8S-key.component';
import { TX21G8SExamComponent } from './components/TX21G8S-exam/TX21G8S-exam.component';
import { TX21G8SKeyComponent } from './components/TX21G8S-key/TX21G8S-key.component';
import { TX19G8SExamComponent } from './components/TX19G8S-exam/TX19G8S-exam.component';
import { TX19G8SKeyComponent } from './components/TX19G8S-key/TX19G8S-key.component';
import { TX18G8SExamComponent } from './components/TX18G8S-exam/TX18G8S-exam.component';
import { TX18G8SKeyComponent } from './components/TX18G8S-key/TX18G8S-key.component';
import { TX22G8SSExamComponent } from './components/TX22G8SS-exam/TX22G8SS-exam.component';
import { TX22G8SSKeyComponent } from './components/TX22G8SS-key/TX22G8SS-key.component';
import { TX21G8SSExamComponent } from './components/TX21G8SS-exam/TX21G8SS-exam.component';
import { TX21G8SSKeyComponent } from './components/TX21G8SS-key/TX21G8SS-key.component';
import { TX19G8SSExamComponent } from './components/TX19G8SS-exam/TX19G8SS-exam.component';
import { TX19G8SSKeyComponent } from './components/TX19G8SS-key/TX19G8SS-key.component';
import { TX18G8SSExamComponent } from './components/TX18G8SS-exam/TX18G8SS-exam.component';
import { TX18G8SSKeyComponent } from './components/TX18G8SS-key/TX18G8SS-key.component';
import { StandardsComponent } from './components/standards/standards.component';
import { KMStandardsComponent } from './components/KM-standards/KM-standards.component';
import { KEStandardsComponent } from './components/KE-standards/KE-standards.component';
import { G1MStandardsComponent } from './components/G1M-standards/G1M-standards.component';
import { G1EStandardsComponent } from './components/G1E-standards/G1E-standards.component';
import { G2MStandardsComponent } from './components/G2M-standards/G2M-standards.component';
import { G2EStandardsComponent } from './components/G2E-standards/G2E-standards.component';
import { G3MStandardsComponent } from './components/G3M-standards/G3M-standards.component';
import { G3EStandardsComponent } from './components/G3E-standards/G3E-standards.component';
import { G4MStandardsComponent } from './components/G4M-standards/G4M-standards.component';
import { G4EStandardsComponent } from './components/G4E-standards/G4E-standards.component';
import { G5MStandardsComponent } from './components/G5M-standards/G5M-standards.component';
import { G5EStandardsComponent } from './components/G5E-standards/G5E-standards.component';
import { G6MStandardsComponent } from './components/G6M-standards/G6M-standards.component';
import { G6EStandardsComponent } from './components/G6E-standards/G6E-standards.component';
import { G7MStandardsComponent } from './components/G7M-standards/G7M-standards.component';
import { G7EStandardsComponent } from './components/G7E-standards/G7E-standards.component';
import { G8MStandardsComponent } from './components/G8M-standards/G8M-standards.component';
import { G8EStandardsComponent } from './components/G8E-standards/G8E-standards.component';
import { HS1EStandardsComponent } from './components/HS1E-standards/HS1E-standards.component';
import { HS2EStandardsComponent } from './components/HS2E-standards/HS2E-standards.component';
import { HSMNQStandardsComponent } from './components/HSM-NQ-standards/HSM-NQ-standards.component';
import { HSMAStandardsComponent } from './components/HSM-A-standards/HSM-A-standards.component';
import { HSMFStandardsComponent } from './components/HSM-F-standards/HSM-F-standards.component';
import { HSMGStandardsComponent } from './components/HSM-G-standards/HSM-G-standards.component';
import { HSMSPStandardsComponent } from './components/HSM-SP-standards/HSM-SP-standards.component';

const routes: Routes = [
  { path: '', redirectTo: 'exams', pathMatch: 'full' },
  { path: 'home', component: HomeComponent },
  { path: 'exams', component: ExamsComponent },
  { path: 'exam/test', component: TestExamComponent },
  { path: 'exam/TX22G3M', component: TX22G3MExamComponent },
  { path: 'exam/TX22G3M/key', component: TX22G3MKeyComponent },
  { path: 'exam/TX21G3M', component: TX21G3MExamComponent },
  { path: 'exam/TX21G3M/key', component: TX21G3MKeyComponent },
  { path: 'exam/TX19G3M', component: TX19G3MExamComponent },
  { path: 'exam/TX19G3M/key', component: TX19G3MKeyComponent },
  { path: 'exam/TX18G3M', component: TX18G3MExamComponent },
  { path: 'exam/TX18G3M/key', component: TX18G3MKeyComponent },
  { path: 'exam/TX17G3M', component: TX17G3MExamComponent },
  { path: 'exam/TX17G3M/key', component: TX17G3MKeyComponent },
  { path: 'exam/TX22G4M', component: TX22G4MExamComponent },
  { path: 'exam/TX22G4M/key', component: TX22G4MKeyComponent },
  { path: 'exam/TX21G4M', component: TX21G4MExamComponent },
  { path: 'exam/TX21G4M/key', component: TX21G4MKeyComponent },
  { path: 'exam/TX19G4M', component: TX19G4MExamComponent },
  { path: 'exam/TX19G4M/key', component: TX19G4MKeyComponent },
  { path: 'exam/TX18G4M', component: TX18G4MExamComponent },
  { path: 'exam/TX18G4M/key', component: TX18G4MKeyComponent },
  { path: 'exam/TX17G4M', component: TX17G4MExamComponent },
  { path: 'exam/TX17G4M/key', component: TX17G4MKeyComponent },
  { path: 'exam/TX22G5S', component: TX22G5SExamComponent },
  { path: 'exam/TX22G5S/key', component: TX22G5SKeyComponent },
  { path: 'exam/TX21G5S', component: TX21G5SExamComponent },
  { path: 'exam/TX21G5S/key', component: TX21G5SKeyComponent },
  { path: 'exam/TX19G5S', component: TX19G5SExamComponent },
  { path: 'exam/TX19G5S/key', component: TX19G5SKeyComponent },
  { path: 'exam/TX18G5S', component: TX18G5SExamComponent },
  { path: 'exam/TX18G5S/key', component: TX18G5SKeyComponent },
  { path: 'exam/TX22G8S', component: TX22G8SExamComponent },
  { path: 'exam/TX22G8S/key', component: TX22G8SKeyComponent },
  { path: 'exam/TX21G8S', component: TX21G8SExamComponent },
  { path: 'exam/TX21G8S/key', component: TX21G8SKeyComponent },
  { path: 'exam/TX19G8S', component: TX19G8SExamComponent },
  { path: 'exam/TX19G8S/key', component: TX19G8SKeyComponent },
  { path: 'exam/TX18G8S', component: TX18G8SExamComponent },
  { path: 'exam/TX18G8S/key', component: TX18G8SKeyComponent },
  { path: 'exam/TX22G8SS', component: TX22G8SSExamComponent },
  { path: 'exam/TX22G8SS/key', component: TX22G8SSKeyComponent },
  { path: 'exam/TX21G8SS', component: TX21G8SSExamComponent },
  { path: 'exam/TX21G8SS/key', component: TX21G8SSKeyComponent },
  { path: 'exam/TX19G8SS', component: TX19G8SSExamComponent },
  { path: 'exam/TX19G8SS/key', component: TX19G8SSKeyComponent },
  { path: 'exam/TX18G8SS', component: TX18G8SSExamComponent },
  { path: 'exam/TX18G8SS/key', component: TX18G8SSKeyComponent },
  { path: 'standards', component: StandardsComponent },
  { path: 'standards/K-Math', component: KMStandardsComponent },
  { path: 'standards/K-English', component: KEStandardsComponent },
  { path: 'standards/G1-Math', component: G1MStandardsComponent },
  { path: 'standards/G1-English', component: G1EStandardsComponent },
  { path: 'standards/G2-Math', component: G2MStandardsComponent },
  { path: 'standards/G2-English', component: G2EStandardsComponent },
  { path: 'standards/G3-Math', component: G3MStandardsComponent },
  { path: 'standards/G3-English', component: G3EStandardsComponent },
  { path: 'standards/G4-Math', component: G4MStandardsComponent },
  { path: 'standards/G4-English', component: G4EStandardsComponent },
  { path: 'standards/G5-Math', component: G5MStandardsComponent },
  { path: 'standards/G5-English', component: G5EStandardsComponent },
  { path: 'standards/G6-Math', component: G6MStandardsComponent },
  { path: 'standards/G6-English', component: G6EStandardsComponent },
  { path: 'standards/G7-Math', component: G7MStandardsComponent },
  { path: 'standards/G7-English', component: G7EStandardsComponent },
  { path: 'standards/G8-Math', component: G8MStandardsComponent },
  { path: 'standards/G8-English', component: G8EStandardsComponent },
  { path: 'standards/HS1-English', component: HS1EStandardsComponent },
  { path: 'standards/HS2-English', component: HS2EStandardsComponent },
  { path: 'standards/HS-Math-Number-Quantity', component: HSMNQStandardsComponent },
  { path: 'standards/HS-Math-Algebra', component: HSMAStandardsComponent },
  { path: 'standards/HS-Math-Functions', component: HSMFStandardsComponent },
  { path: 'standards/HS-Math-Geometry', component: HSMGStandardsComponent },
  { path: 'standards/HS-Math-Statistics-Probability', component: HSMSPStandardsComponent },
  { path: 'problems', component: ProblemsComponent },
  { path: 'about', component: AboutComponent },
  // { path: 'contact', component: ContactComponent },
  { path: 'login', component: LoginComponent },
  { path: 'signup', component: SignupComponent },
  { path: 'profile', component: ProfileComponent }
];

@NgModule({
  imports: [RouterModule.forRoot(routes)],
  exports: [RouterModule]
})
export class AppRoutingModule { }