import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';

import { ExamsComponent } from './components/exams/exams.component';
import { HomeComponent } from './components/home/home.component';
import { ProblemsComponent } from './components/problems/problems.component';
import { AboutComponent } from './components/about/about.component';
import { LoginComponent } from './components/login/login.component';
import { SignupComponent } from './components/signup/signup.component';
import { ProfileComponent } from './components/profile/profile.component';
import { ContactComponent } from './components/contact/contact.component';
import { TestExamComponent } from './components/test-exam/test-exam.component';
import { PA22G3MExamComponent } from './components/PA22G3M-exam/PA22G3M-exam.component';
import { PA22G3MKeyComponent } from './components/PA22G3M-key/PA22G3M-key.component';
import { PA21G3MExamComponent } from './components/PA21G3M-exam/PA21G3M-exam.component';
import { PA21G3MKeyComponent } from './components/PA21G3M-key/PA21G3M-key.component';
import { PA19G3MExamComponent } from './components/PA19G3M-exam/PA19G3M-exam.component';
import { PA19G3MKeyComponent } from './components/PA19G3M-key/PA19G3M-key.component';
import { PA18G3MExamComponent } from './components/PA18G3M-exam/PA18G3M-exam.component';
import { PA18G3MKeyComponent } from './components/PA18G3M-key/PA18G3M-key.component';
import { PA16G3MExamComponent } from './components/PA16G3M-exam/PA16G3M-exam.component';
import { PA16G3MKeyComponent } from './components/PA16G3M-key/PA16G3M-key.component';
import { PA15G3MExamComponent } from './components/PA15G3M-exam/PA15G3M-exam.component';
import { PA15G3MKeyComponent } from './components/PA15G3M-key/PA15G3M-key.component';
import { PA22G4MExamComponent } from './components/PA22G4M-exam/PA22G4M-exam.component';
import { PA22G4MKeyComponent } from './components/PA22G4M-key/PA22G4M-key.component';
import { PA21G4MExamComponent } from './components/PA21G4M-exam/PA21G4M-exam.component';
import { PA21G4MKeyComponent } from './components/PA21G4M-key/PA21G4M-key.component';
import { PA19G4MExamComponent } from './components/PA19G4M-exam/PA19G4M-exam.component';
import { PA19G4MKeyComponent } from './components/PA19G4M-key/PA19G4M-key.component';
import { PA18G4MExamComponent } from './components/PA18G4M-exam/PA18G4M-exam.component';
import { PA18G4MKeyComponent } from './components/PA18G4M-key/PA18G4M-key.component';
import { PA16G4MExamComponent } from './components/PA16G4M-exam/PA16G4M-exam.component';
import { PA16G4MKeyComponent } from './components/PA16G4M-key/PA16G4M-key.component';
import { PA15G4MExamComponent } from './components/PA15G4M-exam/PA15G4M-exam.component';
import { PA15G4MKeyComponent } from './components/PA15G4M-key/PA15G4M-key.component';
import { PA22G4SExamComponent } from './components/PA22G4S-exam/PA22G4S-exam.component';
import { PA22G4SKeyComponent } from './components/PA22G4S-key/PA22G4S-key.component';
import { PA21G4SExamComponent } from './components/PA21G4S-exam/PA21G4S-exam.component';
import { PA21G4SKeyComponent } from './components/PA21G4S-key/PA21G4S-key.component';
import { PA19G4SExamComponent } from './components/PA19G4S-exam/PA19G4S-exam.component';
import { PA19G4SKeyComponent } from './components/PA19G4S-key/PA19G4S-key.component';
import { PA18G4SExamComponent } from './components/PA18G4S-exam/PA18G4S-exam.component';
import { PA18G4SKeyComponent } from './components/PA18G4S-key/PA18G4S-key.component';
import { PA16G4SExamComponent } from './components/PA16G4S-exam/PA16G4S-exam.component';
import { PA16G4SKeyComponent } from './components/PA16G4S-key/PA16G4S-key.component';
import { PA15G4SExamComponent } from './components/PA15G4S-exam/PA15G4S-exam.component';
import { PA15G4SKeyComponent } from './components/PA15G4S-key/PA15G4S-key.component';
import { PA22G5MExamComponent } from './components/PA22G5M-exam/PA22G5M-exam.component';
import { PA22G5MKeyComponent } from './components/PA22G5M-key/PA22G5M-key.component';
import { PA21G5MExamComponent } from './components/PA21G5M-exam/PA21G5M-exam.component';
import { PA21G5MKeyComponent } from './components/PA21G5M-key/PA21G5M-key.component';
import { PA19G5MExamComponent } from './components/PA19G5M-exam/PA19G5M-exam.component';
import { PA19G5MKeyComponent } from './components/PA19G5M-key/PA19G5M-key.component';
import { PA18G5MExamComponent } from './components/PA18G5M-exam/PA18G5M-exam.component';
import { PA18G5MKeyComponent } from './components/PA18G5M-key/PA18G5M-key.component';
import { PA16G5MExamComponent } from './components/PA16G5M-exam/PA16G5M-exam.component';
import { PA16G5MKeyComponent } from './components/PA16G5M-key/PA16G5M-key.component';
import { PA15G5MExamComponent } from './components/PA15G5M-exam/PA15G5M-exam.component';
import { PA15G5MKeyComponent } from './components/PA15G5M-key/PA15G5M-key.component';
import { PA22G6MExamComponent } from './components/PA22G6M-exam/PA22G6M-exam.component';
import { PA22G6MKeyComponent } from './components/PA22G6M-key/PA22G6M-key.component';
import { PA21G6MExamComponent } from './components/PA21G6M-exam/PA21G6M-exam.component';
import { PA21G6MKeyComponent } from './components/PA21G6M-key/PA21G6M-key.component';
import { PA19G6MExamComponent } from './components/PA19G6M-exam/PA19G6M-exam.component';
import { PA19G6MKeyComponent } from './components/PA19G6M-key/PA19G6M-key.component';
import { PA18G6MExamComponent } from './components/PA18G6M-exam/PA18G6M-exam.component';
import { PA18G6MKeyComponent } from './components/PA18G6M-key/PA18G6M-key.component';
import { PA16G6MExamComponent } from './components/PA16G6M-exam/PA16G6M-exam.component';
import { PA16G6MKeyComponent } from './components/PA16G6M-key/PA16G6M-key.component';
import { PA15G6MExamComponent } from './components/PA15G6M-exam/PA15G6M-exam.component';
import { PA15G6MKeyComponent } from './components/PA15G6M-key/PA15G6M-key.component';
import { PA22G7MExamComponent } from './components/PA22G7M-exam/PA22G7M-exam.component';
import { PA22G7MKeyComponent } from './components/PA22G7M-key/PA22G7M-key.component';
import { PA21G7MExamComponent } from './components/PA21G7M-exam/PA21G7M-exam.component';
import { PA21G7MKeyComponent } from './components/PA21G7M-key/PA21G7M-key.component';
import { PA19G7MExamComponent } from './components/PA19G7M-exam/PA19G7M-exam.component';
import { PA19G7MKeyComponent } from './components/PA19G7M-key/PA19G7M-key.component';
import { PA18G7MExamComponent } from './components/PA18G7M-exam/PA18G7M-exam.component';
import { PA18G7MKeyComponent } from './components/PA18G7M-key/PA18G7M-key.component';
import { PA16G7MExamComponent } from './components/PA16G7M-exam/PA16G7M-exam.component';
import { PA16G7MKeyComponent } from './components/PA16G7M-key/PA16G7M-key.component';
import { PA15G7MExamComponent } from './components/PA15G7M-exam/PA15G7M-exam.component';
import { PA15G7MKeyComponent } from './components/PA15G7M-key/PA15G7M-key.component';
import { PA22G8SExamComponent } from './components/PA22G8S-exam/PA22G8S-exam.component';
import { PA22G8SKeyComponent } from './components/PA22G8S-key/PA22G8S-key.component';
import { PA21G8SExamComponent } from './components/PA21G8S-exam/PA21G8S-exam.component';
import { PA21G8SKeyComponent } from './components/PA21G8S-key/PA21G8S-key.component';
import { PA19G8SExamComponent } from './components/PA19G8S-exam/PA19G8S-exam.component';
import { PA19G8SKeyComponent } from './components/PA19G8S-key/PA19G8S-key.component';
import { PA18G8SExamComponent } from './components/PA18G8S-exam/PA18G8S-exam.component';
import { PA18G8SKeyComponent } from './components/PA18G8S-key/PA18G8S-key.component';
import { PA16G8SExamComponent } from './components/PA16G8S-exam/PA16G8S-exam.component';
import { PA16G8SKeyComponent } from './components/PA16G8S-key/PA16G8S-key.component';
import { PA15G8SExamComponent } from './components/PA15G8S-exam/PA15G8S-exam.component';
import { PA15G8SKeyComponent } from './components/PA15G8S-key/PA15G8S-key.component';
import { TX22G3MExamComponent } from './components/TX22G3M-exam/TX22G3M-exam.component';
import { TX22G3MKeyComponent } from './components/TX22G3M-key/TX22G3M-key.component';
import { TX21G3MExamComponent } from './components/TX21G3M-exam/TX21G3M-exam.component';
import { TX21G3MKeyComponent } from './components/TX21G3M-key/TX21G3M-key.component';
import { TX19G3MExamComponent } from './components/TX19G3M-exam/TX19G3M-exam.component';
import { TX19G3MKeyComponent } from './components/TX19G3M-key/TX19G3M-key.component';
import { TX18G3MExamComponent } from './components/TX18G3M-exam/TX18G3M-exam.component';
import { TX18G3MKeyComponent } from './components/TX18G3M-key/TX18G3M-key.component';
import { TX17G3MExamComponent } from './components/TX17G3M-exam/TX17G3M-exam.component';
import { TX17G3MKeyComponent } from './components/TX17G3M-key/TX17G3M-key.component';
import { TX22G4MExamComponent } from './components/TX22G4M-exam/TX22G4M-exam.component';
import { TX22G4MKeyComponent } from './components/TX22G4M-key/TX22G4M-key.component';
import { TX21G4MExamComponent } from './components/TX21G4M-exam/TX21G4M-exam.component';
import { TX21G4MKeyComponent } from './components/TX21G4M-key/TX21G4M-key.component';
import { TX19G4MExamComponent } from './components/TX19G4M-exam/TX19G4M-exam.component';
import { TX19G4MKeyComponent } from './components/TX19G4M-key/TX19G4M-key.component';
import { TX18G4MExamComponent } from './components/TX18G4M-exam/TX18G4M-exam.component';
import { TX18G4MKeyComponent } from './components/TX18G4M-key/TX18G4M-key.component';
import { TX17G4MExamComponent } from './components/TX17G4M-exam/TX17G4M-exam.component';
import { TX17G4MKeyComponent } from './components/TX17G4M-key/TX17G4M-key.component';
import { TX22G5MExamComponent } from './components/TX22G5M-exam/TX22G5M-exam.component';
import { TX22G5MKeyComponent } from './components/TX22G5M-key/TX22G5M-key.component';
import { TX21G5MExamComponent } from './components/TX21G5M-exam/TX21G5M-exam.component';
import { TX21G5MKeyComponent } from './components/TX21G5M-key/TX21G5M-key.component';
import { TX19G5MExamComponent } from './components/TX19G5M-exam/TX19G5M-exam.component';
import { TX19G5MKeyComponent } from './components/TX19G5M-key/TX19G5M-key.component';
import { TX18G5MExamComponent } from './components/TX18G5M-exam/TX18G5M-exam.component';
import { TX18G5MKeyComponent } from './components/TX18G5M-key/TX18G5M-key.component';
import { TX17G5MExamComponent } from './components/TX17G5M-exam/TX17G5M-exam.component';
import { TX17G5MKeyComponent } from './components/TX17G5M-key/TX17G5M-key.component';
import { TX22G5SExamComponent } from './components/TX22G5S-exam/TX22G5S-exam.component';
import { TX22G5SKeyComponent } from './components/TX22G5S-key/TX22G5S-key.component';
import { TX21G5SExamComponent } from './components/TX21G5S-exam/TX21G5S-exam.component';
import { TX21G5SKeyComponent } from './components/TX21G5S-key/TX21G5S-key.component';
import { TX19G5SExamComponent } from './components/TX19G5S-exam/TX19G5S-exam.component';
import { TX19G5SKeyComponent } from './components/TX19G5S-key/TX19G5S-key.component';
import { TX18G5SExamComponent } from './components/TX18G5S-exam/TX18G5S-exam.component';
import { TX18G5SKeyComponent } from './components/TX18G5S-key/TX18G5S-key.component';
import { TX22G6MExamComponent } from './components/TX22G6M-exam/TX22G6M-exam.component';
import { TX22G6MKeyComponent } from './components/TX22G6M-key/TX22G6M-key.component';
import { TX21G6MExamComponent } from './components/TX21G6M-exam/TX21G6M-exam.component';
import { TX21G6MKeyComponent } from './components/TX21G6M-key/TX21G6M-key.component';
import { TX19G6MExamComponent } from './components/TX19G6M-exam/TX19G6M-exam.component';
import { TX19G6MKeyComponent } from './components/TX19G6M-key/TX19G6M-key.component';
import { TX18G6MExamComponent } from './components/TX18G6M-exam/TX18G6M-exam.component';
import { TX18G6MKeyComponent } from './components/TX18G6M-key/TX18G6M-key.component';
import { TX17G6MExamComponent } from './components/TX17G6M-exam/TX17G6M-exam.component';
import { TX17G6MKeyComponent } from './components/TX17G6M-key/TX17G6M-key.component';
import { TX22G7MExamComponent } from './components/TX22G7M-exam/TX22G7M-exam.component';
import { TX22G7MKeyComponent } from './components/TX22G7M-key/TX22G7M-key.component';
import { TX21G7MExamComponent } from './components/TX21G7M-exam/TX21G7M-exam.component';
import { TX21G7MKeyComponent } from './components/TX21G7M-key/TX21G7M-key.component';
import { TX19G7MExamComponent } from './components/TX19G7M-exam/TX19G7M-exam.component';
import { TX19G7MKeyComponent } from './components/TX19G7M-key/TX19G7M-key.component';
import { TX18G7MExamComponent } from './components/TX18G7M-exam/TX18G7M-exam.component';
import { TX18G7MKeyComponent } from './components/TX18G7M-key/TX18G7M-key.component';
import { TX17G7MExamComponent } from './components/TX17G7M-exam/TX17G7M-exam.component';
import { TX17G7MKeyComponent } from './components/TX17G7M-key/TX17G7M-key.component';
import { TX22G8MExamComponent } from './components/TX22G8M-exam/TX22G8M-exam.component';
import { TX22G8MKeyComponent } from './components/TX22G8M-key/TX22G8M-key.component';
import { TX21G8MExamComponent } from './components/TX21G8M-exam/TX21G8M-exam.component';
import { TX21G8MKeyComponent } from './components/TX21G8M-key/TX21G8M-key.component';
import { TX19G8MExamComponent } from './components/TX19G8M-exam/TX19G8M-exam.component';
import { TX19G8MKeyComponent } from './components/TX19G8M-key/TX19G8M-key.component';
import { TX18G8MExamComponent } from './components/TX18G8M-exam/TX18G8M-exam.component';
import { TX18G8MKeyComponent } from './components/TX18G8M-key/TX18G8M-key.component';
import { TX17G8MExamComponent } from './components/TX17G8M-exam/TX17G8M-exam.component';
import { TX17G8MKeyComponent } from './components/TX17G8M-key/TX17G8M-key.component';
import { TX22G8SExamComponent } from './components/TX22G8S-exam/TX22G8S-exam.component';
import { TX22G8SKeyComponent } from './components/TX22G8S-key/TX22G8S-key.component';
import { TX21G8SExamComponent } from './components/TX21G8S-exam/TX21G8S-exam.component';
import { TX21G8SKeyComponent } from './components/TX21G8S-key/TX21G8S-key.component';
import { TX19G8SExamComponent } from './components/TX19G8S-exam/TX19G8S-exam.component';
import { TX19G8SKeyComponent } from './components/TX19G8S-key/TX19G8S-key.component';
import { TX18G8SExamComponent } from './components/TX18G8S-exam/TX18G8S-exam.component';
import { TX18G8SKeyComponent } from './components/TX18G8S-key/TX18G8S-key.component';
import { TX22G8SSExamComponent } from './components/TX22G8SS-exam/TX22G8SS-exam.component';
import { TX22G8SSKeyComponent } from './components/TX22G8SS-key/TX22G8SS-key.component';
import { TX21G8SSExamComponent } from './components/TX21G8SS-exam/TX21G8SS-exam.component';
import { TX21G8SSKeyComponent } from './components/TX21G8SS-key/TX21G8SS-key.component';
import { TX19G8SSExamComponent } from './components/TX19G8SS-exam/TX19G8SS-exam.component';
import { TX19G8SSKeyComponent } from './components/TX19G8SS-key/TX19G8SS-key.component';
import { TX18G8SSExamComponent } from './components/TX18G8SS-exam/TX18G8SS-exam.component';
import { TX18G8SSKeyComponent } from './components/TX18G8SS-key/TX18G8SS-key.component';
import { StandardsComponent } from './components/standards/standards.component';
import { KMStandardsComponent } from './components/KM-standards/KM-standards.component';
import { KEStandardsComponent } from './components/KE-standards/KE-standards.component';
import { G1MStandardsComponent } from './components/G1M-standards/G1M-standards.component';
import { G1EStandardsComponent } from './components/G1E-standards/G1E-standards.component';
import { G2MStandardsComponent } from './components/G2M-standards/G2M-standards.component';
import { G2EStandardsComponent } from './components/G2E-standards/G2E-standards.component';
import { G3MStandardsComponent } from './components/G3M-standards/G3M-standards.component';
import { G3EStandardsComponent } from './components/G3E-standards/G3E-standards.component';
import { G4MStandardsComponent } from './components/G4M-standards/G4M-standards.component';
import { G4EStandardsComponent } from './components/G4E-standards/G4E-standards.component';
import { G5MStandardsComponent } from './components/G5M-standards/G5M-standards.component';
import { G5EStandardsComponent } from './components/G5E-standards/G5E-standards.component';
import { G6MStandardsComponent } from './components/G6M-standards/G6M-standards.component';
import { G6EStandardsComponent } from './components/G6E-standards/G6E-standards.component';
import { G7MStandardsComponent } from './components/G7M-standards/G7M-standards.component';
import { G7EStandardsComponent } from './components/G7E-standards/G7E-standards.component';
import { G8MStandardsComponent } from './components/G8M-standards/G8M-standards.component';
import { G8EStandardsComponent } from './components/G8E-standards/G8E-standards.component';
import { HS1EStandardsComponent } from './components/HS1E-standards/HS1E-standards.component';
import { HS2EStandardsComponent } from './components/HS2E-standards/HS2E-standards.component';
import { HSMNQStandardsComponent } from './components/HSM-NQ-standards/HSM-NQ-standards.component';
import { HSMAStandardsComponent } from './components/HSM-A-standards/HSM-A-standards.component';
import { HSMFStandardsComponent } from './components/HSM-F-standards/HSM-F-standards.component';
import { HSMGStandardsComponent } from './components/HSM-G-standards/HSM-G-standards.component';
import { HSMSPStandardsComponent } from './components/HSM-SP-standards/HSM-SP-standards.component';

const routes: Routes = [
  { path: '', redirectTo: 'exams', pathMatch: 'full' },
  { path: 'about', component: AboutComponent },
  // { path: 'contact', component: ContactComponent },
  { path: 'exams', component: ExamsComponent },
  { path: 'problems', component: ProblemsComponent },
  { path: 'standards', component: StandardsComponent },
  { path: 'home', component: HomeComponent },
  { path: 'login', component: LoginComponent },
  { path: 'signup', component: SignupComponent },
  { path: 'profile', component: ProfileComponent },
  { path: 'exam/test', component: TestExamComponent },
  { path: 'exam/PA22G3M', component: PA22G3MExamComponent },
  { path: 'exam/PA22G3M/key', component: PA22G3MKeyComponent },
  { path: 'exam/PA21G3M', component: PA21G3MExamComponent },
  { path: 'exam/PA21G3M/key', component: PA21G3MKeyComponent },
  { path: 'exam/PA19G3M', component: PA19G3MExamComponent },
  { path: 'exam/PA19G3M/key', component: PA19G3MKeyComponent },
  { path: 'exam/PA18G3M', component: PA18G3MExamComponent },
  { path: 'exam/PA18G3M/key', component: PA18G3MKeyComponent },
  { path: 'exam/PA16G3M', component: PA16G3MExamComponent },
  { path: 'exam/PA16G3M/key', component: PA16G3MKeyComponent },
  { path: 'exam/PA15G3M', component: PA15G3MExamComponent },
  { path: 'exam/PA15G3M/key', component: PA15G3MKeyComponent },
  { path: 'exam/PA22G4M', component: PA22G4MExamComponent },
  { path: 'exam/PA22G4M/key', component: PA22G4MKeyComponent },
  { path: 'exam/PA21G4M', component: PA21G4MExamComponent },
  { path: 'exam/PA21G4M/key', component: PA21G4MKeyComponent },
  { path: 'exam/PA19G4M', component: PA19G4MExamComponent },
  { path: 'exam/PA19G4M/key', component: PA19G4MKeyComponent },
  { path: 'exam/PA18G4M', component: PA18G4MExamComponent },
  { path: 'exam/PA18G4M/key', component: PA18G4MKeyComponent },
  { path: 'exam/PA16G4M', component: PA16G4MExamComponent },
  { path: 'exam/PA16G4M/key', component: PA16G4MKeyComponent },
  { path: 'exam/PA15G4M', component: PA15G4MExamComponent },
  { path: 'exam/PA15G4M/key', component: PA15G4MKeyComponent },
  { path: 'exam/PA22G4S', component: PA22G4SExamComponent },
  { path: 'exam/PA22G4S/key', component: PA22G4SKeyComponent },
  { path: 'exam/PA21G4S', component: PA21G4SExamComponent },
  { path: 'exam/PA21G4S/key', component: PA21G4SKeyComponent },
  { path: 'exam/PA19G4S', component: PA19G4SExamComponent },
  { path: 'exam/PA19G4S/key', component: PA19G4SKeyComponent },
  { path: 'exam/PA18G4S', component: PA18G4SExamComponent },
  { path: 'exam/PA18G4S/key', component: PA18G4SKeyComponent },
  { path: 'exam/PA16G4S', component: PA16G4SExamComponent },
  { path: 'exam/PA16G4S/key', component: PA16G4SKeyComponent },
  { path: 'exam/PA15G4S', component: PA15G4SExamComponent },
  { path: 'exam/PA15G4S/key', component: PA15G4SKeyComponent },
  { path: 'exam/PA22G5M', component: PA22G5MExamComponent },
  { path: 'exam/PA22G5M/key', component: PA22G5MKeyComponent },
  { path: 'exam/PA21G5M', component: PA21G5MExamComponent },
  { path: 'exam/PA21G5M/key', component: PA21G5MKeyComponent },
  { path: 'exam/PA19G5M', component: PA19G5MExamComponent },
  { path: 'exam/PA19G5M/key', component: PA19G5MKeyComponent },
  { path: 'exam/PA18G5M', component: PA18G5MExamComponent },
  { path: 'exam/PA18G5M/key', component: PA18G5MKeyComponent },
  { path: 'exam/PA16G5M', component: PA16G5MExamComponent },
  { path: 'exam/PA16G5M/key', component: PA16G5MKeyComponent },
  { path: 'exam/PA15G5M', component: PA15G5MExamComponent },
  { path: 'exam/PA15G5M/key', component: PA15G5MKeyComponent },
  { path: 'exam/PA22G6M', component: PA22G6MExamComponent },
  { path: 'exam/PA22G6M/key', component: PA22G6MKeyComponent },
  { path: 'exam/PA21G6M', component: PA21G6MExamComponent },
  { path: 'exam/PA21G6M/key', component: PA21G6MKeyComponent },
  { path: 'exam/PA19G6M', component: PA19G6MExamComponent },
  { path: 'exam/PA19G6M/key', component: PA19G6MKeyComponent },
  { path: 'exam/PA18G6M', component: PA18G6MExamComponent },
  { path: 'exam/PA18G6M/key', component: PA18G6MKeyComponent },
  { path: 'exam/PA16G6M', component: PA16G6MExamComponent },
  { path: 'exam/PA16G6M/key', component: PA16G6MKeyComponent },
  { path: 'exam/PA15G6M', component: PA15G6MExamComponent },
  { path: 'exam/PA15G6M/key', component: PA15G6MKeyComponent },
  { path: 'exam/PA22G7M', component: PA22G7MExamComponent },
  { path: 'exam/PA22G7M/key', component: PA22G7MKeyComponent },
  { path: 'exam/PA21G7M', component: PA21G7MExamComponent },
  { path: 'exam/PA21G7M/key', component: PA21G7MKeyComponent },
  { path: 'exam/PA19G7M', component: PA19G7MExamComponent },
  { path: 'exam/PA19G7M/key', component: PA19G7MKeyComponent },
  { path: 'exam/PA18G7M', component: PA18G7MExamComponent },
  { path: 'exam/PA18G7M/key', component: PA18G7MKeyComponent },
  { path: 'exam/PA16G7M', component: PA16G7MExamComponent },
  { path: 'exam/PA16G7M/key', component: PA16G7MKeyComponent },
  { path: 'exam/PA15G7M', component: PA15G7MExamComponent },
  { path: 'exam/PA15G7M/key', component: PA15G7MKeyComponent },
  { path: 'exam/PA22G8S', component: PA22G8SExamComponent },
  { path: 'exam/PA22G8S/key', component: PA22G8SKeyComponent },
  { path: 'exam/PA21G8S', component: PA21G8SExamComponent },
  { path: 'exam/PA21G8S/key', component: PA21G8SKeyComponent },
  { path: 'exam/PA19G8S', component: PA19G8SExamComponent },
  { path: 'exam/PA19G8S/key', component: PA19G8SKeyComponent },
  { path: 'exam/PA18G8S', component: PA18G8SExamComponent },
  { path: 'exam/PA18G8S/key', component: PA18G8SKeyComponent },
  { path: 'exam/PA16G8S', component: PA16G8SExamComponent },
  { path: 'exam/PA16G8S/key', component: PA16G8SKeyComponent },
  { path: 'exam/PA15G8S', component: PA15G8SExamComponent },
  { path: 'exam/PA15G8S/key', component: PA15G8SKeyComponent },
  { path: 'exam/TX22G3M', component: TX22G3MExamComponent },
  { path: 'exam/TX22G3M/key', component: TX22G3MKeyComponent },
  { path: 'exam/TX21G3M', component: TX21G3MExamComponent },
  { path: 'exam/TX21G3M/key', component: TX21G3MKeyComponent },
  { path: 'exam/TX19G3M', component: TX19G3MExamComponent },
  { path: 'exam/TX19G3M/key', component: TX19G3MKeyComponent },
  { path: 'exam/TX18G3M', component: TX18G3MExamComponent },
  { path: 'exam/TX18G3M/key', component: TX18G3MKeyComponent },
  { path: 'exam/TX17G3M', component: TX17G3MExamComponent },
  { path: 'exam/TX17G3M/key', component: TX17G3MKeyComponent },
  { path: 'exam/TX22G4M', component: TX22G4MExamComponent },
  { path: 'exam/TX22G4M/key', component: TX22G4MKeyComponent },
  { path: 'exam/TX21G4M', component: TX21G4MExamComponent },
  { path: 'exam/TX21G4M/key', component: TX21G4MKeyComponent },
  { path: 'exam/TX19G4M', component: TX19G4MExamComponent },
  { path: 'exam/TX19G4M/key', component: TX19G4MKeyComponent },
  { path: 'exam/TX18G4M', component: TX18G4MExamComponent },
  { path: 'exam/TX18G4M/key', component: TX18G4MKeyComponent },
  { path: 'exam/TX17G4M', component: TX17G4MExamComponent },
  { path: 'exam/TX17G4M/key', component: TX17G4MKeyComponent },
  { path: 'exam/TX22G5M', component: TX22G5MExamComponent },
  { path: 'exam/TX22G5M/key', component: TX22G5MKeyComponent },
  { path: 'exam/TX21G5M', component: TX21G5MExamComponent },
  { path: 'exam/TX21G5M/key', component: TX21G5MKeyComponent },
  { path: 'exam/TX19G5M', component: TX19G5MExamComponent },
  { path: 'exam/TX19G5M/key', component: TX19G5MKeyComponent },
  { path: 'exam/TX18G5M', component: TX18G5MExamComponent },
  { path: 'exam/TX18G5M/key', component: TX18G5MKeyComponent },
  { path: 'exam/TX17G5M', component: TX17G5MExamComponent },
  { path: 'exam/TX17G5M/key', component: TX17G5MKeyComponent },
  { path: 'exam/TX22G5S', component: TX22G5SExamComponent },
  { path: 'exam/TX22G5S/key', component: TX22G5SKeyComponent },
  { path: 'exam/TX21G5S', component: TX21G5SExamComponent },
  { path: 'exam/TX21G5S/key', component: TX21G5SKeyComponent },
  { path: 'exam/TX19G5S', component: TX19G5SExamComponent },
  { path: 'exam/TX19G5S/key', component: TX19G5SKeyComponent },
  { path: 'exam/TX18G5S', component: TX18G5SExamComponent },
  { path: 'exam/TX18G5S/key', component: TX18G5SKeyComponent },
  { path: 'exam/TX22G6M', component: TX22G6MExamComponent },
  { path: 'exam/TX22G6M/key', component: TX22G6MKeyComponent },
  { path: 'exam/TX21G6M', component: TX21G6MExamComponent },
  { path: 'exam/TX21G6M/key', component: TX21G6MKeyComponent },
  { path: 'exam/TX19G6M', component: TX19G6MExamComponent },
  { path: 'exam/TX19G6M/key', component: TX19G6MKeyComponent },
  { path: 'exam/TX18G6M', component: TX18G6MExamComponent },
  { path: 'exam/TX18G6M/key', component: TX18G6MKeyComponent },
  { path: 'exam/TX17G6M', component: TX17G6MExamComponent },
  { path: 'exam/TX17G6M/key', component: TX17G6MKeyComponent },
  { path: 'exam/TX22G7M', component: TX22G7MExamComponent },
  { path: 'exam/TX22G7M/key', component: TX22G7MKeyComponent },
  { path: 'exam/TX21G7M', component: TX21G7MExamComponent },
  { path: 'exam/TX21G7M/key', component: TX21G7MKeyComponent },
  { path: 'exam/TX19G7M', component: TX19G7MExamComponent },
  { path: 'exam/TX19G7M/key', component: TX19G7MKeyComponent },
  { path: 'exam/TX18G7M', component: TX18G7MExamComponent },
  { path: 'exam/TX18G7M/key', component: TX18G7MKeyComponent },
  { path: 'exam/TX17G7M', component: TX17G7MExamComponent },
  { path: 'exam/TX17G7M/key', component: TX17G7MKeyComponent },
  { path: 'exam/TX22G8M', component: TX22G8MExamComponent },
  { path: 'exam/TX22G8M/key', component: TX22G8MKeyComponent },
  { path: 'exam/TX21G8M', component: TX21G8MExamComponent },
  { path: 'exam/TX21G8M/key', component: TX21G8MKeyComponent },
  { path: 'exam/TX19G8M', component: TX19G8MExamComponent },
  { path: 'exam/TX19G8M/key', component: TX19G8MKeyComponent },
  { path: 'exam/TX18G8M', component: TX18G8MExamComponent },
  { path: 'exam/TX18G8M/key', component: TX18G8MKeyComponent },
  { path: 'exam/TX17G8M', component: TX17G8MExamComponent },
  { path: 'exam/TX17G8M/key', component: TX17G8MKeyComponent },
  { path: 'exam/TX22G8S', component: TX22G8SExamComponent },
  { path: 'exam/TX22G8S/key', component: TX22G8SKeyComponent },
  { path: 'exam/TX21G8S', component: TX21G8SExamComponent },
  { path: 'exam/TX21G8S/key', component: TX21G8SKeyComponent },
  { path: 'exam/TX19G8S', component: TX19G8SExamComponent },
  { path: 'exam/TX19G8S/key', component: TX19G8SKeyComponent },
  { path: 'exam/TX18G8S', component: TX18G8SExamComponent },
  { path: 'exam/TX18G8S/key', component: TX18G8SKeyComponent },
  { path: 'exam/TX22G8SS', component: TX22G8SSExamComponent },
  { path: 'exam/TX22G8SS/key', component: TX22G8SSKeyComponent },
  { path: 'exam/TX21G8SS', component: TX21G8SSExamComponent },
  { path: 'exam/TX21G8SS/key', component: TX21G8SSKeyComponent },
  { path: 'exam/TX19G8SS', component: TX19G8SSExamComponent },
  { path: 'exam/TX19G8SS/key', component: TX19G8SSKeyComponent },
  { path: 'exam/TX18G8SS', component: TX18G8SSExamComponent },
  { path: 'exam/TX18G8SS/key', component: TX18G8SSKeyComponent },
  { path: 'standards/K-Math', component: KMStandardsComponent },
  { path: 'standards/K-English', component: KEStandardsComponent },
  { path: 'standards/G1-Math', component: G1MStandardsComponent },
  { path: 'standards/G1-English', component: G1EStandardsComponent },
  { path: 'standards/G2-Math', component: G2MStandardsComponent },
  { path: 'standards/G2-English', component: G2EStandardsComponent },
  { path: 'standards/G3-Math', component: G3MStandardsComponent },
  { path: 'standards/G3-English', component: G3EStandardsComponent },
  { path: 'standards/G4-Math', component: G4MStandardsComponent },
  { path: 'standards/G4-English', component: G4EStandardsComponent },
  { path: 'standards/G5-Math', component: G5MStandardsComponent },
  { path: 'standards/G5-English', component: G5EStandardsComponent },
  { path: 'standards/G6-Math', component: G6MStandardsComponent },
  { path: 'standards/G6-English', component: G6EStandardsComponent },
  { path: 'standards/G7-Math', component: G7MStandardsComponent },
  { path: 'standards/G7-English', component: G7EStandardsComponent },
  { path: 'standards/G8-Math', component: G8MStandardsComponent },
  { path: 'standards/G8-English', component: G8EStandardsComponent },
  { path: 'standards/HS1-English', component: HS1EStandardsComponent },
  { path: 'standards/HS2-English', component: HS2EStandardsComponent },
  { path: 'standards/HS-Math-Number-Quantity', component: HSMNQStandardsComponent },
  { path: 'standards/HS-Math-Algebra', component: HSMAStandardsComponent },
  { path: 'standards/HS-Math-Functions', component: HSMFStandardsComponent },
  { path: 'standards/HS-Math-Geometry', component: HSMGStandardsComponent },
  { path: 'standards/HS-Math-Statistics-Probability', component: HSMSPStandardsComponent }
];

@NgModule({
  imports: [RouterModule.forRoot(routes)],
  exports: [RouterModule]
})
export class AppRoutingModule { }